// <auto-generated />
using System;
using Carrefour.Desafio.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Carrefour.Desafio.ORM.Migrations
{
    [DbContext(typeof(DefaultContext))]
    partial class DefaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Carrefour.Desafio.Domain.Entities.Lancamento", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier")
                    .HasDefaultValueSql("NEWID()")
                    .HasColumnName("LAN_ID");

                b.Property<DateTime>("DataLancamento")
                    .IsRequired()
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("GETDATE()")
                    .HasColumnName("DT_LANCAMENTO");

                b.Property<string>("TipoLancamento")
                    .IsRequired()
                    .HasMaxLength(10)
                    .HasColumnType("varchar(10)")
                    .HasColumnName("TP_LANCAMENTO");

                b.Property<decimal>("ValorLancamento")
                    .IsRequired()
                    .HasColumnType("decimal(18,2)")
                    .HasColumnName("VLR_LANCAMENTO");

                b.Property<string>("DescricaoLancamento")
                    .HasMaxLength(255)
                    .HasColumnType("nvarchar(255)")
                    .HasColumnName("DES_LANCAMENTO");

                b.Property<string>("CategoriaLancamento")
                    .HasMaxLength(100)
                    .HasColumnType("nvarchar(100)")
                    .HasColumnName("CAT_LANCAMENTO");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("GETDATE()")
                    .HasColumnName("CREATED_AT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime")
                    .HasColumnName("UPDATED_AT");

                b.HasKey("Id");
                b.ToTable("TBL_LANCAMENTO");
            });
        }
    }
}
