// <auto-generated />
using System;
using Carrefour.Desafio.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Carrefour.Desafio.ORM.Migrations
{
    [DbContext(typeof(DefaultContext))]
    partial class DefaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Carrefour.Desafio.Domain.Entities.User", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier")
                    .HasDefaultValueSql("NEWID()")
                    .HasColumnName("USER_ID");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("varchar(50)")
                    .HasColumnName("TXT_USERNAME");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)")
                    .HasColumnName("TXT_PASSWORD");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("varchar(100)")
                    .HasColumnName("TXT_EMAIL");

                b.Property<string>("Phone")
                    .HasMaxLength(20)
                    .HasColumnType("varchar(20)")
                    .HasColumnName("TXT_PHONE");

                b.Property<string>("Status")
                    .HasMaxLength(20)
                    .HasColumnType("varchar(20)")
                    .HasColumnName("TXT_STATUS");

                b.Property<string>("Role")
                    .HasMaxLength(20)
                    .HasColumnType("varchar(20)")
                    .HasColumnName("TXT_ROLE");

                b.HasKey("Id");
                b.ToTable("TBL_USER");
            });

        }
    }
}
