export enum FuncionalidadeEnum {
    INSERRIR_USUARIO = "INSERRIR_USUARIO",
    EDITAR_USUARIO = "EDITAR_USUARIO",
    CONSULTAR_USUARIO = "CONSULTAR_USUARIO",
    EXCLUIR_USUARIO = "EXCLUIR_USUARIO",
    VINCULAR_PERFIL = "VINCULAR_PERFIL",
    VINCULAR_UNIDADE = "VINCULAR_UNIDADE"
 }