// <auto-generated />
using System;
using Carrefour.Desafio.ORM;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

#nullable disable

namespace Carrefour.Desafio.ORM.Migrations
{
    [DbContext(typeof(DefaultContext))]
    partial class DefaultContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("Carrefour.Desafio.Domain.Entities.Consolidado", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uniqueidentifier")
                    .HasDefaultValueSql("NEWID()")
                    .HasColumnName("CON_ID");

                b.Property<DateTime>("DataConsolidado")
                    .IsRequired()
                    .HasColumnType("date")
                    .HasColumnName("DT_CONSOLIDADO");

                b.Property<decimal>("ValorDebito")
                    .IsRequired()
                    .HasColumnType("decimal(18,2)")
                    .HasColumnName("VLR_DEB")
                    .HasDefaultValue(0);

                b.Property<decimal>("ValorCredito")
                    .IsRequired()
                    .HasColumnType("decimal(18,2)")
                    .HasColumnName("VLR_CRE")
                    .HasDefaultValue(0);

                b.Property<decimal>("SaldoFinal")
                    .IsRequired()
                    .HasColumnType("decimal(18,2)")
                    .HasColumnName("VLR_SLD_FINAL")
                    .HasDefaultValue(0);

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("datetime")
                    .HasDefaultValueSql("GETDATE()")
                    .HasColumnName("CREATED_AT");

                b.Property<DateTime?>("UpdatedAt")
                    .HasColumnType("datetime")
                    .HasColumnName("UPDATED_AT");

                b.HasKey("Id");
                b.HasIndex("DataConsolidado").IsUnique();
                b.ToTable("TBL_CONSOLIDADO");
            });
        }
    }
}
