version: '3.8'

networks:
  monitoring:
    driver: bridge

volumes:
  data:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Spike@888
      - MSSQL_PID=Express
      - DB_NAME=banco
    ports:
      - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data
    networks:
      - monitoring
