CREATE TABLE TBL_USER (
    USER_ID uniqueidentifier NOT NULL DEFAULT NEWID(),
    TXT_USERNAME VARCHAR(50) NOT NULL,
    TXT_PASSWORD VARCHAR(100) NOT NULL,
    TXT_EMAIL VARCHAR(100) NOT NULL,
    TXT_PHONE VARCHAR(20) NULL,
    TXT_STATUS VARCHAR(20) NULL,
    TXT_ROLE VARCHAR(20) NULL,
    CREATED_AT DATETIME NOT NULL DEFAULT GETDATE(),
    UPDATED_AT DATETIME NULL,
    CONSTRAINT PK_TBL_USER PRIMARY KEY (USER_ID)
);
