CREATE TABLE TBL_CONSOLIDADO (
    CON_ID UNIQUEIDENTIFIER  DEFAULT NEWID(),
    DT_CONSOLIDADO DATE NOT NULL UNIQUE,
    VLR_DEB DECIMAL(18,2) NOT NULL DEFAULT 0,
    VLR_CRE DECIMAL(18,2) NOT NULL DEFAULT 0,
    VLR_SLD_FINAL DECIMAL(18,2) NOT NULL DEFAULT 0,
	CREATED_AT DATETIME DEFAULT GETDATE(),
	UPDATED_AT DATETIME NULL,
	CONSTRAINT PK_TBL_CONSOLIDADO PRIMARY KEY (CON_ID)
);





